POST http://localhost:3333/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlOTQ0MjE0ZC1hZjU2LTQ0ZmYtYTIwYi0zZWYwNGNmMjlkYjUiLCJyb2xlIjoiYW5hbHlzdCIsImlhdCI6MTc1NzI4NzE5MX0.CY0s45JlH2gOy1IJ0HToM0OfGseHMKuY9OZ1r4x3Cys

{
    "name": "Hot",
    "email": "hot@gmail.com",
    "password": "12345678",
    "role": "supervisor"
}

###

POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMzQ2YTc0ZC1mZTQ4LTQ2ZGUtYTFiNC03YWRlZDZhMTc2NTYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTcyODU5MDZ9.TGmC9f424sql0jt74B98RX_tDWjiChuPIrR4C9RRHmU

{
    "title": "Curso de Marketing 39283"
}

###

GET http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMzQ2YTc0ZC1mZTQ4LTQ2ZGUtYTFiNC03YWRlZDZhMTc2NTYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTcyODUzODF9.g0Mf8VQfUbLThj6FQP0ezRvY9prRg7vPXXhzPhYsAIk

###

GET http://localhost:3333/courses/4a8fd892-4239-4e86-b30c-23b11126c20a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMGIwODk5MC00YzQxLTQ1NjgtYWNlNy1kZmUxMDI3ODgwNjQiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NzIwMDE3OX0.8T1eakPdM3OLOQml6Tv4CW84kaqoa01oOgRV-UFv1oY


###

POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email": "hot@gmail.com",
    "password": "12345678"
}