POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Cur"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/d7d442c0-d80d-4753-bcfe-87441a7615cb